#pragma once

enum TOKENR_TYPE
{
	TOKENR_GAMEOBJECT = 0,
	TOKENR_PrefabInstance = 1,
	TOKENR_TRANSFORM = 2,
	TOKENR_LOCAL_ROTATION = 3,
	TOKENR_LOCAL_POSITION = 4,
	TOKENR_LOCAL_SCALE = 5,
	TOKENR_CAMERA = 6,
};